# Generated by Django 3.2.9 on 2022-01-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220123_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default='YYYY-MM-DD', null=True),
        ),
    ]
